name: PiGen build

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      
      - name: Check directory content
        run: |
          ls

      - name: Docker Kosmos Pi Gen build
        run: |
          "bash runner-build.sh"
