name: PiGen build

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."		￼
          # - name: echo "Build stage1, stage2 image"
          #   run: |
          #     sudo time ./build.sh | tee deploy/build-complete.log
     - name: Docker Kosmos Pi Gen build
       run: |
         bash runner-build.sh
